kafka:
  brokers:
    - kafka-broker-1:19092
    - kafka-broker-2:19092
    - kafka-broker-3:19092

schemaRegistry:
  enabled: true
  urls: ["http://schema-registry:18081"]

redpanda:
  adminApi:
    enabled: false
    urls: ["http://kafka-broker-1:9644"]

connect:
  enabled: false
